default: &default
   adapter: postgresql
   database: bambu
   username: postgres
   password: 123
   host: localhost

development:
   adapter: postgresql
   database: bambu
   username: postgres
   password: 123
   host: localhost

test:
   adapter: postgresql
   database: bambu
   username: postgres
   password: 123
   host: localhost
   
production:
   adapter: postgresql
   database: bambu
   username: postgres
   password: 123
   host: localhost
