default: &default
   adapter: postgresql
   database: bambup
   username: postgres
   password: 12345
   host: localhost

development:
   adapter: postgresql
   database: bambup
   username: postgres
   password: 12345
   host: localhost

test:
   adapter: postgresql
   database: bambup
   username: postgres
   password: 12345
   host: localhost
   
production:
   adapter: postgresql
   database: bambup
   username: postgres
   password: 12345
   host: localhost
